# Generated by Django 3.0.5 on 2020-04-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=120)),
                ('Cheveaux', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)])),
                ('type', models.CharField(choices=[('Monophasé', 'Monophasé'), ('Triphasé', 'Triphasé')], max_length=120)),
                ('Amperage', models.PositiveIntegerField()),
                ('couplage', models.CharField(choices=[('Parallèle Etoile', 'Parallèle Etoile'), ('Parallèle Triangle', 'Parallèle Triangle'), ('Serie Etoile', 'Serie Etoile'), ('Serie Triangle', 'Serie Triangle')], max_length=120)),
                ('nb_spire_principale', models.PositiveIntegerField()),
                ('nb_spire_aux', models.PositiveIntegerField(blank=True, null=True)),
                ('longeur_rotor_mm', models.PositiveIntegerField()),
                ('diametre_rotor_mm', models.PositiveIntegerField()),
            ],
        ),
    ]
